export const locationCodeToCountryName1: Record<string, string> = {
  C: 'Canada',
  J: 'Mars',
  K: 'Contiguous United States',
  Y: 'Australia',
}

export const locationCodeToCountryName3: Record<string, string> = {
  U: 'Russia',
  Z: 'Mainland China',
}

export const locationCodeToCountryName2: Record<string, string> = {
  AG: 'Solomon Islands',
  AN: 'Nauru Islands',
  AY: 'Papua New Guinea',
  BG: 'Greenland',
  BI: 'Iceland',
  BK: 'Kosovo',
  DA: 'Algeria',
  DB: 'Benin',
  DF: 'Burkina Faso',
  DG: 'Ghana',
  DI: 'Ivory Coast',
  DN: 'Nigeria',
  DR: 'Niger',
  DT: 'Tunisia',
  DX: 'Togo',
  EB: 'Belgium',
  ED: 'Germany',
  EE: 'Estonia',
  EF: 'Finland',
  EG: 'United Kingdom',
  EH: 'Netherlands',
  EI: 'Ireland',
  EK: 'Denmark',
  EL: 'Luxembourg',
  EN: 'Norway',
  EP: 'Poland',
  ES: 'Sweden',
  ET: 'Germany',
  EV: 'Latvia',
  EY: 'Lithuania',
  FA: 'South Africa',
  FB: 'Botswana',
  FC: 'Congo',
  FD: 'Swaziland',
  FE: 'Republic of Central Africa',
  FG: 'Equatorial Guinea',
  FH: 'Ascension Islands',
  FI: 'Mauritius',
  FJ: 'Diego Garcia',
  FK: 'Cameroon',
  FL: 'Zambia',
  FM: 'Madagascar',
  FN: 'Angola',
  FO: 'Gabon',
  FP: 'Sao Tome',
  FQ: 'Mozambique',
  FS: 'Seychelles',
  FT: 'Chad',
  FV: 'Zimbabwe',
  FW: 'Malawi',
  FX: 'Lesotho',
  FY: 'Namibia',
  FZ: 'Zaire',
  GA: 'Mali',
  GB: 'Gambia',
  GC: 'Canary Islands',
  GE: 'Melilla',
  GF: 'Sierra Leone',
  GG: 'Guinea Bissau',
  GL: 'Liberia',
  GM: 'Morocco',
  GO: 'Senegal',
  GQ: 'Mauritania',
  GU: 'Guinea',
  GV: 'Cape Verde',
  HA: 'Ethiopia',
  HB: 'Burundi',
  HD: 'Djibouti',
  HE: 'Egypt',
  HH: 'Eritrea',
  HK: 'Kenya',
  HL: 'Libya',
  HR: 'Rwanda',
  HS: 'Sudan',
  HT: 'Tanzania',
  HU: 'Uganda',
  LA: 'Albania',
  LB: 'Bulgaria',
  LC: 'Cyprus',
  LD: 'Croatia',
  LE: 'Spain',
  LF: 'France',
  LG: 'Greece',
  LH: 'Hungary',
  LI: 'Italy',
  LJ: 'Slovenia',
  LK: 'Czech Republic',
  LL: 'Israel',
  LM: 'Malta',
  LO: 'Austria',
  LP: 'Portugal',
  LQ: 'Bosnia and Herzegovinia',
  LR: 'Romania',
  LS: 'Switzerland',
  LT: 'Turkey',
  LU: 'Moldova',
  LW: 'Macedonia',
  LX: 'Gibralter',
  LY: 'Yugoslavia',
  LZ: 'Slovakia',
  MB: 'Turks and Caicos Islands',
  MD: 'Dominican Republic',
  MG: 'Guatemala',
  MH: 'Honduras',
  MK: 'Jamaica',
  MM: 'Mexico',
  MN: 'Nicaragua',
  MP: 'Panama',
  MR: 'Costa Rica',
  MS: 'El Salvador',
  MT: 'Haiti',
  MU: 'Cuba',
  MW: 'Cayman Islands',
  MY: 'Bahamas',
  MZ: 'Belize',
  NC: 'Cook Islands',
  NF: 'Fiji',
  NG: 'Kiribati Islands',
  NI: 'Niue Islands',
  NL: 'Wallis Islands',
  NS: 'American Samoa',
  NT: 'Tahiti',
  NV: 'Vanuatu',
  NW: 'Noumea',
  NZ: 'New Zealand',
  OA: 'Afghanistan',
  OB: 'Bahrain',
  OE: 'Saudi Arabia',
  OI: 'Iran',
  OJ: 'Jordan',
  OK: 'Kuwait',
  OL: 'Lebanon',
  OM: 'United Arab Emirates',
  OO: 'Oman',
  OP: 'Pakistan',
  OR: 'Iraq',
  OS: 'Syria',
  OT: 'Qatar',
  OY: 'Yemen',
  PA: 'Alaska',
  PG: 'Guam',
  PH: 'Hawaii',
  PJ: 'Johnston Islands',
  PK: 'Marshall Islands',
  PL: 'Line Islands',
  PM: 'Midway Islands',
  PT: 'Micronesia',
  PW: 'Wake Islands',
  RC: 'Taiwan',
  RJ: 'Japan',
  RK: 'Korea',
  RO: 'Okinawa Islands',
  RP: 'Philippines',
  SA: 'Argentina',
  SB: 'Brazil',
  SC: 'Chile',
  SE: 'Equador',
  SG: 'Paraguay',
  SK: 'Colombia',
  SL: 'Bolivia',
  SM: 'Surinam',
  SO: 'French Guyana',
  SP: 'Peru',
  SU: 'Uruguay',
  SV: 'Venezuela',
  SY: 'Guyana',
  TA: 'Antigua and Barbuda',
  TB: 'Barbados',
  TD: 'Dominica',
  TF: 'French Antilles',
  TG: 'Grenada',
  TI: 'U.S. Virgin Islands',
  TJ: 'Puerto Rico',
  TK: 'St. Kitts Islands',
  TL: 'St. Lucia',
  TN: 'Aruba / Netherlands Antilles',
  TQ: 'Anguilla',
  TT: 'Monserrat Islands',
  TU: 'Trinidad and Tobago',
  TV: 'U.K Virgin Islands',
  TX: 'Bermuda',
  UA: 'Kazakhstan and Kyrgyzstan',
  UB: 'Azerbiajan',
  UC: 'Kyrgyzstan',
  UD: 'Armenia',
  UG: 'Georgia',
  UK: 'Ukraine',
  UM: 'Belarus',
  UT: 'Uzbekistan, Turkmenistan and Tadjikistan',
  VA: 'India',
  VC: 'Sri Lanka',
  VD: 'Cambodia',
  VE: 'India',
  VG: 'Bangladesh',
  VH: 'Hongkong',
  VI: 'India',
  VL: 'Laos',
  VM: 'Macau',
  VN: 'Nepal',
  VO: 'India',
  VR: 'Maldives',
  VT: 'Thailand',
  VV: 'Vietnam',
  VY: 'Myanmar',
  WA: 'Indonesia',
  WB: 'Brunei',
  WI: 'Indonesia',
  WM: 'Malaysia',
  WR: 'Indonesia',
  WS: 'Singapore',
  ZK: 'North Korea',
  ZM: 'Mongolia',
};

export const locationCodeToContinent: Record<string, string> = {
  A: 'Australia',
  B: 'North America',
  C: 'North America',
  D: 'Africa',
  E: 'Europe',
  F: 'Africa',
  G: 'Africa',
  H: 'Africa',
  J: 'Mars',
  K: 'North America',
  L: 'Europe',
  M: 'North America',
  N: 'Australia',
  O: 'Asia',
  P: 'North America',
  R: 'Asia',
  S: 'South America',
  T: 'North America',
  U: 'Europe',
  V: 'Asia',
  W: 'Asia',
  Y: 'Australia',
  Z: 'Asia',
};
